/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matrix */
        get: operations["matrix_api_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gitflow/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gitflow Rules */
        get: operations["gitflow_rules_api_gitflow_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Apps */
        get: operations["list_apps_api_apps_get"];
        put?: never;
        /** Add App */
        post: operations["add_app_api_apps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Init App */
        post: operations["init_app_api_apps_init_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Detail */
        get: operations["app_detail_api_apps__id__get"];
        put?: never;
        post?: never;
        /** Remove App */
        delete: operations["remove_app_api_apps__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync App */
        post: operations["sync_app_api_apps__id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push App */
        post: operations["push_app_api_apps__id__push_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/gitflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Gitflow */
        get: operations["app_gitflow_api_apps__id__gitflow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Commits */
        get: operations["app_commits_api_apps__id__commits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Tags */
        get: operations["app_tags_api_apps__id__tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Releases */
        get: operations["app_releases_api_apps__id__releases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Branches */
        get: operations["app_branches_api_apps__id__branches_get"];
        put?: never;
        /** Start Branch */
        post: operations["start_branch_api_apps__id__branches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** App Release */
        post: operations["app_release_api_apps__id__release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** App Deploy */
        post: operations["app_deploy_api_apps__id__deploy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Diagnose */
        get: operations["app_diagnose_api_apps__id__diagnose_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checkout */
        post: operations["checkout_api_apps__id__checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/pull-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Propose Pull Request */
        get: operations["propose_pull_request_api_apps__id__pull_request_get"];
        put?: never;
        /** Open Pull Request */
        post: operations["open_pull_request_api_apps__id__pull_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Manifest */
        get: operations["read_manifest_api_apps__id__manifest_get"];
        /** Write Manifest */
        put: operations["write_manifest_api_apps__id__manifest_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/cloud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Cloud */
        post: operations["set_cloud_api_apps__id__cloud_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Service */
        post: operations["add_service_api_apps__id__services_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit */
        post: operations["commit_api_apps__id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddAppRequest */
        AddAppRequest: {
            /** Url */
            url: string;
            /** Name */
            name?: string | null;
            credentials?: components["schemas"]["SourceCredentials"] | null;
        };
        /** AppDetail */
        AppDetail: {
            /** Id */
            id: string;
            /** Url */
            url: string;
            /**
             * Default Branch
             * @default
             */
            default_branch: string;
            project: components["schemas"]["AppMeta"];
            /** Source Host */
            source_host: {
                [key: string]: string;
            };
            /** Deploy */
            deploy: {
                [key: string]: unknown;
            };
            /** Release */
            release: {
                [key: string]: string;
            };
            /** Services */
            services: {
                [key: string]: unknown;
            };
            /** Last Version */
            last_version?: string | null;
            /** Branch */
            branch: string;
            /** Latest Tag */
            latest_tag?: string | null;
            /** Clean */
            clean: boolean;
        };
        /** AppEntry */
        AppEntry: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Path */
            path: string;
            /**
             * Default Branch
             * @default
             */
            default_branch: string;
        };
        /** AppMeta */
        AppMeta: {
            /**
             * Name
             * @default
             */
            name: string;
            /** Type */
            type?: string | null;
            /** Stack */
            stack?: string | null;
            /** Template */
            template?: string | null;
            /** Language */
            language?: string | null;
            /** Ci */
            ci?: string | null;
        };
        /** AppRow */
        AppRow: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Exists */
            exists: boolean;
            /** Language */
            language?: string | null;
            /** Type */
            type?: string | null;
            /** Last Version */
            last_version?: string | null;
            /** Branch */
            branch?: string | null;
        };
        /** Branch */
        Branch: {
            /** Name */
            name: string;
            /** Date */
            date: string;
            /** Kind */
            kind?: string | null;
            /** Protected */
            protected: boolean;
            /** Problem */
            problem?: string | null;
        };
        /** BranchResult */
        BranchResult: {
            /** Branch */
            branch: string;
            /** Base */
            base: string;
            /** Pushed */
            pushed: boolean;
        };
        /** CheckoutRequest */
        CheckoutRequest: {
            /** Branch */
            branch: string;
        };
        /** CloudRequest */
        CloudRequest: {
            /** Target */
            target: string;
        };
        /** Commit */
        Commit: {
            /** Sha */
            sha: string;
            /** Subject */
            subject: string;
            /** Author */
            author: string;
            /** Date */
            date: string;
        };
        /** CommitBranch */
        CommitBranch: {
            /** Kind */
            kind: string;
            /** Code */
            code: string;
            /** Slug */
            slug?: string | null;
        };
        /** CommitPullRequest */
        CommitPullRequest: {
            /** Number */
            number: number;
            /** Url */
            url: string;
        };
        /** CommitRequest */
        CommitRequest: {
            /** Message */
            message: string;
            /**
             * Push
             * @default false
             */
            push: boolean;
            branch?: components["schemas"]["CommitBranch"] | null;
            /**
             * Pull Request
             * @default false
             */
            pull_request: boolean;
            credentials?: components["schemas"]["SourceCredentials"] | null;
        };
        /** CommitResult */
        CommitResult: {
            /** Sha */
            sha: string;
            /** Branch */
            branch: string;
            /** Pushed */
            pushed: boolean;
            pull_request?: components["schemas"]["CommitPullRequest"] | null;
        };
        /** DeployRequest */
        DeployRequest: {
            /** Stage */
            stage?: string | null;
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
        };
        /** DeployResult */
        DeployResult: {
            /** Target */
            target: string;
            /** Ok */
            ok: boolean;
            /** Version */
            version: string;
            /** Url */
            url?: string | null;
            /** Error */
            error?: string | null;
        };
        /** Diagnosis */
        Diagnosis: {
            /** Ok */
            ok: boolean;
            /** Target */
            target: string;
            /**
             * Status
             * @default
             */
            status: string;
            /** Version */
            version?: string | null;
            /** Url */
            url?: string | null;
            /**
             * Details
             * @default {}
             */
            details: {
                [key: string]: string;
            };
        };
        /** GitflowReport */
        GitflowReport: {
            /** Branch */
            branch: string;
            /** Problems */
            problems: string[];
            /** Checked Commits */
            checked_commits: number;
            /** Ok */
            ok: boolean;
        };
        /** GitflowRules */
        GitflowRules: {
            /** Kinds */
            kinds: string[];
            /** Protected */
            protected: string[];
            /** Types */
            types: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InitRequest */
        InitRequest: {
            /** Type */
            type: string;
            /** Stack */
            stack?: string | null;
            /** Template */
            template?: string | null;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Package Name */
            package_name?: string | null;
            /** Github Owner */
            github_owner?: string | null;
            /** Ci */
            ci?: string | null;
            /** Cloud */
            cloud?: string | null;
            /**
             * Git Init
             * @default true
             */
            git_init: boolean;
            /**
             * Push
             * @default false
             */
            push: boolean;
            /**
             * Private
             * @default false
             */
            private: boolean;
            credentials?: components["schemas"]["SourceCredentials"] | null;
        };
        /** InitResult */
        InitResult: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Url */
            url: string;
            /** Template */
            template: string;
            /** Cloud */
            cloud?: string | null;
            /** Pushed */
            pushed: boolean;
        };
        /** ManifestBody */
        ManifestBody: {
            /** Content */
            content: string;
        };
        /** Matrix */
        Matrix: {
            /** Projects */
            projects: components["schemas"]["MatrixProject"][];
            /** Clouds */
            clouds: components["schemas"]["MatrixCloud"][];
            /** Services */
            services: components["schemas"]["MatrixService"][];
        };
        /** MatrixCloud */
        MatrixCloud: {
            /** Name */
            name: string;
            /** Types */
            types: string[];
            /** Languages */
            languages: string[];
            /** Description */
            description: string;
        };
        /** MatrixProject */
        MatrixProject: {
            /** Type */
            type: string;
            /** Stack */
            stack: string;
            /** Template */
            template: string;
            /** Default */
            default: boolean;
            /** Description */
            description: string;
        };
        /** MatrixService */
        MatrixService: {
            /** Name */
            name: string;
            /** Providers */
            providers: string[];
            /** Description */
            description: string;
        };
        /** PullRequestProposal */
        PullRequestProposal: {
            /** Head */
            head: string;
            /** Base */
            base: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Commits */
            commits: string[];
        };
        /** PullRequestRequest */
        PullRequestRequest: {
            /** Base */
            base?: string | null;
            /** Title */
            title?: string | null;
            /** Body */
            body?: string | null;
            /**
             * Draft
             * @default false
             */
            draft: boolean;
            credentials?: components["schemas"]["SourceCredentials"] | null;
        };
        /** PullRequestResult */
        PullRequestResult: {
            /** Number */
            number: number;
            /** Url */
            url: string;
        };
        /** PushRequest */
        PushRequest: {
            /**
             * Private
             * @default false
             */
            private: boolean;
            credentials?: components["schemas"]["SourceCredentials"] | null;
        };
        /** PushResult */
        PushResult: {
            /** Id */
            id: string;
            /** Url */
            url: string;
        };
        /** Release */
        Release: {
            /** Tag */
            tag: string;
            /** Version */
            version: string;
            /** Date */
            date: string;
            /** Sha */
            sha: string;
            /** Subject */
            subject: string;
            /** Prerelease */
            prerelease: boolean;
            /** Latest */
            latest: boolean;
        };
        /** ReleasePreview */
        ReleasePreview: {
            /** Current */
            current: string;
            /** Next */
            next: string;
            /** Changelog */
            changelog: string;
            /** Branch */
            branch: string;
            /** Prerelease */
            prerelease: boolean;
            /** Dry Run */
            dry_run: boolean;
        };
        /** ReleaseRequest */
        ReleaseRequest: {
            /**
             * Level
             * @default patch
             */
            level: string;
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
            /** Branch */
            branch?: string | null;
            /** Component */
            component?: string | null;
            credentials?: components["schemas"]["SourceCredentials"] | null;
        };
        /** ServiceRequest */
        ServiceRequest: {
            /** Name */
            name: string;
            /** Provider */
            provider?: string | null;
        };
        /** SourceCredentials */
        SourceCredentials: {
            /** Kind */
            kind: string;
            /** Token */
            token: string;
            /** Username */
            username?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Owner */
            owner?: string | null;
        };
        /** StartBranchRequest */
        StartBranchRequest: {
            /** Kind */
            kind: string;
            /** Code */
            code: string;
            /** Slug */
            slug?: string | null;
            /**
             * Push
             * @default true
             */
            push: boolean;
            credentials?: components["schemas"]["SourceCredentials"] | null;
        };
        /** SyncRequest */
        SyncRequest: {
            credentials?: components["schemas"]["SourceCredentials"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Version */
        Version: {
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    matrix_api_matrix_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Matrix"];
                };
            };
        };
    };
    gitflow_rules_api_gitflow_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitflowRules"];
                };
            };
        };
    };
    list_apps_api_apps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppRow"][];
                };
            };
        };
    };
    add_app_api_apps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddAppRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    init_app_api_apps_init_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_detail_api_apps__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_app_api_apps__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_app_api_apps__id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SyncRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_app_api_apps__id__push_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_gitflow_api_apps__id__gitflow_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitflowReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_commits_api_apps__id__commits_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Commit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_tags_api_apps__id__tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_releases_api_apps__id__releases_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Release"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_branches_api_apps__id__branches_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_branch_api_apps__id__branches_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartBranchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_release_api_apps__id__release_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleasePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_deploy_api_apps__id__deploy_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeployRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeployResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_diagnose_api_apps__id__diagnose_get: {
        parameters: {
            query?: {
                stage?: string | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagnosis"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkout_api_apps__id__checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_pull_request_api_apps__id__pull_request_get: {
        parameters: {
            query?: {
                base?: string | null;
                title?: string | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullRequestProposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_pull_request_api_apps__id__pull_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PullRequestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullRequestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_manifest_api_apps__id__manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManifestBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_manifest_api_apps__id__manifest_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManifestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManifestBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_cloud_api_apps__id__cloud_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloudRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_service_api_apps__id__services_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_api_apps__id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
