/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matrix */
        get: operations["matrix_api_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gitflow/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gitflow Rules */
        get: operations["gitflow_rules_api_gitflow_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Add Project */
        post: operations["add_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project */
        get: operations["project_api_projects__id__get"];
        put?: never;
        post?: never;
        /** Remove Project */
        delete: operations["remove_project_api_projects__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/gitflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Gitflow */
        get: operations["project_gitflow_api_projects__id__gitflow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Commits */
        get: operations["project_commits_api_projects__id__commits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Tags */
        get: operations["project_tags_api_projects__id__tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Branches */
        get: operations["project_branches_api_projects__id__branches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Project Release */
        post: operations["project_release_api_projects__id__release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Project Deploy */
        post: operations["project_deploy_api_projects__id__deploy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Diagnose */
        get: operations["project_diagnose_api_projects__id__diagnose_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddProject */
        AddProject: {
            /** Path */
            path: string;
        };
        /** Branch */
        Branch: {
            /** Name */
            name: string;
            /** Date */
            date: string;
            /** Kind */
            kind?: string | null;
            /** Protected */
            protected: boolean;
            /** Problem */
            problem?: string | null;
        };
        /** Commit */
        Commit: {
            /** Sha */
            sha: string;
            /** Subject */
            subject: string;
            /** Author */
            author: string;
            /** Date */
            date: string;
        };
        /** DeployRequest */
        DeployRequest: {
            /** Stage */
            stage?: string | null;
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
        };
        /** DeployResult */
        DeployResult: {
            /** Target */
            target: string;
            /** Ok */
            ok: boolean;
            /** Version */
            version: string;
            /** Url */
            url?: string | null;
            /** Error */
            error?: string | null;
        };
        /** Diagnosis */
        Diagnosis: {
            /** Ok */
            ok: boolean;
            /** Target */
            target: string;
            /**
             * Status
             * @default
             */
            status: string;
            /** Version */
            version?: string | null;
            /** Url */
            url?: string | null;
            /**
             * Details
             * @default {}
             */
            details: {
                [key: string]: string;
            };
        };
        /** GitflowReport */
        GitflowReport: {
            /** Branch */
            branch: string;
            /** Problems */
            problems: string[];
            /** Checked Commits */
            checked_commits: number;
            /** Ok */
            ok: boolean;
        };
        /** GitflowRules */
        GitflowRules: {
            /** Kinds */
            kinds: string[];
            /** Protected */
            protected: string[];
            /** Types */
            types: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Matrix */
        Matrix: {
            /** Projects */
            projects: components["schemas"]["MatrixProject"][];
            /** Clouds */
            clouds: components["schemas"]["MatrixCloud"][];
            /** Services */
            services: components["schemas"]["MatrixService"][];
        };
        /** MatrixCloud */
        MatrixCloud: {
            /** Name */
            name: string;
            /** Types */
            types: string[];
            /** Languages */
            languages: string[];
            /** Description */
            description: string;
        };
        /** MatrixProject */
        MatrixProject: {
            /** Type */
            type: string;
            /** Stack */
            stack: string;
            /** Template */
            template: string;
            /** Default */
            default: boolean;
            /** Description */
            description: string;
        };
        /** MatrixService */
        MatrixService: {
            /** Name */
            name: string;
            /** Providers */
            providers: string[];
            /** Description */
            description: string;
        };
        /** ProjectDetail */
        ProjectDetail: {
            /** Id */
            id: string;
            /** Path */
            path: string;
            project: components["schemas"]["ProjectMeta"];
            /** Source Host */
            source_host: {
                [key: string]: string;
            };
            /** Deploy */
            deploy: {
                [key: string]: unknown;
            };
            /** Release */
            release: {
                [key: string]: string;
            };
            /** Services */
            services: {
                [key: string]: unknown;
            };
            /** Last Version */
            last_version?: string | null;
            /** Branch */
            branch: string;
            /** Latest Tag */
            latest_tag?: string | null;
            /** Clean */
            clean: boolean;
        };
        /** ProjectEntry */
        ProjectEntry: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /** ProjectMeta */
        ProjectMeta: {
            /**
             * Name
             * @default
             */
            name: string;
            /** Type */
            type?: string | null;
            /** Stack */
            stack?: string | null;
            /** Template */
            template?: string | null;
            /** Language */
            language?: string | null;
            /** Ci */
            ci?: string | null;
        };
        /** ProjectRow */
        ProjectRow: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Exists */
            exists: boolean;
            /** Language */
            language?: string | null;
            /** Type */
            type?: string | null;
            /** Last Version */
            last_version?: string | null;
            /** Branch */
            branch?: string | null;
        };
        /** ReleasePreview */
        ReleasePreview: {
            /** Current */
            current: string;
            /** Next */
            next: string;
            /** Changelog */
            changelog: string;
            /** Dry Run */
            dry_run: boolean;
        };
        /** ReleaseRequest */
        ReleaseRequest: {
            /**
             * Level
             * @default patch
             */
            level: string;
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Version */
        Version: {
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    matrix_api_matrix_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Matrix"];
                };
            };
        };
    };
    gitflow_rules_api_gitflow_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitflowRules"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRow"][];
                };
            };
        };
    };
    add_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddProject"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_api_projects__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_project_api_projects__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_gitflow_api_projects__id__gitflow_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitflowReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_commits_api_projects__id__commits_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Commit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_tags_api_projects__id__tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_branches_api_projects__id__branches_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_release_api_projects__id__release_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleasePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_deploy_api_projects__id__deploy_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeployRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeployResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_diagnose_api_projects__id__diagnose_get: {
        parameters: {
            query?: {
                stage?: string | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagnosis"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
