/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matrix */
        get: operations["matrix_api_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gitflow/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gitflow Rules */
        get: operations["gitflow_rules_api_gitflow_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Apps */
        get: operations["list_apps_api_apps_get"];
        put?: never;
        /** Add App */
        post: operations["add_app_api_apps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Init App
         * @description Generate an app from the matrix into a new workspace and register it.
         *
         *     Nothing leaves the server unless `push` is set, which creates the
         *     remote repository through the template's [source_host].
         */
        post: operations["init_app_api_apps_init_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push App
         * @description Create the remote repository through the app's [source_host] and push main.
         *
         *     Needs ACTION_PLATFORM_GITHUB_TOKEN (or GH_TOKEN) in the API's environment.
         */
        post: operations["push_app_api_apps__id__push_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync App */
        post: operations["sync_app_api_apps__id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Detail */
        get: operations["app_detail_api_apps__id__get"];
        put?: never;
        post?: never;
        /** Remove App */
        delete: operations["remove_app_api_apps__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/gitflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Gitflow */
        get: operations["app_gitflow_api_apps__id__gitflow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Commits */
        get: operations["app_commits_api_apps__id__commits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Tags */
        get: operations["app_tags_api_apps__id__tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Branches */
        get: operations["app_branches_api_apps__id__branches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** App Release */
        post: operations["app_release_api_apps__id__release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** App Deploy */
        post: operations["app_deploy_api_apps__id__deploy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{id}/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Diagnose */
        get: operations["app_diagnose_api_apps__id__diagnose_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddApp */
        AddApp: {
            /** Url */
            url: string;
            /** Name */
            name?: string | null;
        };
        /** AppDetail */
        AppDetail: {
            /** Id */
            id: string;
            /** Url */
            url: string;
            /**
             * Default Branch
             * @default
             */
            default_branch: string;
            project: components["schemas"]["AppMeta"];
            /** Source Host */
            source_host: {
                [key: string]: string;
            };
            /** Deploy */
            deploy: {
                [key: string]: unknown;
            };
            /** Release */
            release: {
                [key: string]: string;
            };
            /** Services */
            services: {
                [key: string]: unknown;
            };
            /** Last Version */
            last_version?: string | null;
            /** Branch */
            branch: string;
            /** Latest Tag */
            latest_tag?: string | null;
            /** Clean */
            clean: boolean;
        };
        /** AppEntry */
        AppEntry: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Path */
            path: string;
            /**
             * Default Branch
             * @default
             */
            default_branch: string;
        };
        /** AppMeta */
        AppMeta: {
            /**
             * Name
             * @default
             */
            name: string;
            /** Type */
            type?: string | null;
            /** Stack */
            stack?: string | null;
            /** Template */
            template?: string | null;
            /** Language */
            language?: string | null;
            /** Ci */
            ci?: string | null;
        };
        /** AppRow */
        AppRow: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Exists */
            exists: boolean;
            /** Language */
            language?: string | null;
            /** Type */
            type?: string | null;
            /** Last Version */
            last_version?: string | null;
            /** Branch */
            branch?: string | null;
        };
        /** Branch */
        Branch: {
            /** Name */
            name: string;
            /** Date */
            date: string;
            /** Kind */
            kind?: string | null;
            /** Protected */
            protected: boolean;
            /** Problem */
            problem?: string | null;
        };
        /** Commit */
        Commit: {
            /** Sha */
            sha: string;
            /** Subject */
            subject: string;
            /** Author */
            author: string;
            /** Date */
            date: string;
        };
        /** DeployRequest */
        DeployRequest: {
            /** Stage */
            stage?: string | null;
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
        };
        /** DeployResult */
        DeployResult: {
            /** Target */
            target: string;
            /** Ok */
            ok: boolean;
            /** Version */
            version: string;
            /** Url */
            url?: string | null;
            /** Error */
            error?: string | null;
        };
        /** Diagnosis */
        Diagnosis: {
            /** Ok */
            ok: boolean;
            /** Target */
            target: string;
            /**
             * Status
             * @default
             */
            status: string;
            /** Version */
            version?: string | null;
            /** Url */
            url?: string | null;
            /**
             * Details
             * @default {}
             */
            details: {
                [key: string]: string;
            };
        };
        /** GitflowReport */
        GitflowReport: {
            /** Branch */
            branch: string;
            /** Problems */
            problems: string[];
            /** Checked Commits */
            checked_commits: number;
            /** Ok */
            ok: boolean;
        };
        /** GitflowRules */
        GitflowRules: {
            /** Kinds */
            kinds: string[];
            /** Protected */
            protected: string[];
            /** Types */
            types: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InitRequest */
        InitRequest: {
            /** Type */
            type: string;
            /** Stack */
            stack?: string | null;
            /** Template */
            template?: string | null;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Package Name */
            package_name?: string | null;
            /** Github Owner */
            github_owner?: string | null;
            /** Ci */
            ci?: string | null;
            /** Cloud */
            cloud?: string | null;
            /**
             * Git Init
             * @default true
             */
            git_init: boolean;
            /**
             * Push
             * @default false
             */
            push: boolean;
            /**
             * Private
             * @default false
             */
            private: boolean;
            credentials?: components["schemas"]["SourceCredentials"] | null;
        };
        /** InitResult */
        InitResult: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Url */
            url: string;
            /** Template */
            template: string;
            /** Cloud */
            cloud?: string | null;
            /** Pushed */
            pushed: boolean;
        };
        /** Matrix */
        Matrix: {
            /** Projects */
            projects: components["schemas"]["MatrixProject"][];
            /** Clouds */
            clouds: components["schemas"]["MatrixCloud"][];
            /** Services */
            services: components["schemas"]["MatrixService"][];
        };
        /** MatrixCloud */
        MatrixCloud: {
            /** Name */
            name: string;
            /** Types */
            types: string[];
            /** Languages */
            languages: string[];
            /** Description */
            description: string;
        };
        /** MatrixProject */
        MatrixProject: {
            /** Type */
            type: string;
            /** Stack */
            stack: string;
            /** Template */
            template: string;
            /** Default */
            default: boolean;
            /** Description */
            description: string;
        };
        /** MatrixService */
        MatrixService: {
            /** Name */
            name: string;
            /** Providers */
            providers: string[];
            /** Description */
            description: string;
        };
        /** PushRequest */
        PushRequest: {
            /**
             * Private
             * @default false
             */
            private: boolean;
            credentials?: components["schemas"]["SourceCredentials"] | null;
        };
        /** PushResult */
        PushResult: {
            /** Id */
            id: string;
            /** Url */
            url: string;
        };
        /** ReleasePreview */
        ReleasePreview: {
            /** Current */
            current: string;
            /** Next */
            next: string;
            /** Changelog */
            changelog: string;
            /** Dry Run */
            dry_run: boolean;
        };
        /** ReleaseRequest */
        ReleaseRequest: {
            /**
             * Level
             * @default patch
             */
            level: string;
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
            credentials?: components["schemas"]["SourceCredentials"] | null;
        };
        /** SourceCredentials */
        SourceCredentials: {
            /** Kind */
            kind: string;
            /** Token */
            token: string;
            /** Username */
            username?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Owner */
            owner?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Version */
        Version: {
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    matrix_api_matrix_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Matrix"];
                };
            };
        };
    };
    gitflow_rules_api_gitflow_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitflowRules"];
                };
            };
        };
    };
    list_apps_api_apps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppRow"][];
                };
            };
        };
    };
    add_app_api_apps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddApp"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    init_app_api_apps_init_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_app_api_apps__id__push_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_app_api_apps__id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_detail_api_apps__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_app_api_apps__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_gitflow_api_apps__id__gitflow_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitflowReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_commits_api_apps__id__commits_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Commit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_tags_api_apps__id__tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_branches_api_apps__id__branches_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_release_api_apps__id__release_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleasePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_deploy_api_apps__id__deploy_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeployRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeployResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_diagnose_api_apps__id__diagnose_get: {
        parameters: {
            query?: {
                stage?: string | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagnosis"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
