
[variables]
main_domain = "${domain}"
postgres_password = "${password:32}"
auth_secret = "${password:64}"
api_token = "${password:64}"

[config]
[[config.domains]]
serviceName = "web"
port = 3000
host = "${main_domain}"

[config.env]
PUBLIC_URL = "https://${main_domain}"
POSTGRES_PASSWORD = "${postgres_password}"
BETTER_AUTH_SECRET = "${auth_secret}"
AP_API_TOKEN = "${api_token}"
AP_SENTRY_DSN_API = ""
AP_SENTRY_DSN_WEB = ""
